services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
      
  cico:
    image: kapil537/cico-cicosmarttracko:latest
    container_name: cico
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql 
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    ports:
      - "8080:8081"
 


